INCLUDEFLAGS = -I ../mystring/ -I ../mesinkarakter/

all: mmesinbaris.c mesinbaris.c
	gcc mesinbaris.c mmesinbaris.c ../mesinkarakter/mesinkarakter.c ../mystring/mystring.c $(INCLUDEFLAGS) -o mesinbaris
